### ISSUE TITLE
Release v1.5.0 related Documentation

### ISSUE THREAD

**Issue by devendran-m** [casper-network/docs#429]
This is a high-level epic which will be used to track all the documentation additions, updates, and changes required for the Release v1.5.0 in Casper Network.

- [x] https://github.com/casper-network/docs/issues/159
- [x] https://github.com/casper-network/docs/issues/384
- [x] https://github.com/casper-network/docs/issues/430
- [x] https://github.com/casper-network/docs/issues/533 - [_Related JS SDK ticket #158_]( https://github.com/casper-ecosystem/casper-js-sdk/issues/158)
- [x] https://github.com/casper-network/docs/issues/534
- [x] https://github.com/casper-network/docs/issues/539
- [x] https://github.com/casper-network/docs/issues/540 
- [x] #542 - [_Related JS SDK ticket #155_]( https://github.com/casper-ecosystem/casper-js-sdk/issues/155)
